---
title: "Analytical profession profiles"
---

```{r global-options, include=FALSE}
# Set echo=false for all chunks
knitr::opts_chunk$set(echo=FALSE)
```

Below are links to profession-specific profiles. These contain the outputs present on the summary statistics page, filtered by profession. Only professions with 20 or more respondents are included.

## Profession sample sizes

``` {r}

library(magrittr)

if(!exists("data")) stop("Dataframe called data not available. This should be in the function enviroment of render_main_site. Check that this is available in this enviroment.")

profs <- dplyr::select(data, prof_non_CS:prof_none_CS)
prof_freqs <- carsurvey2::calc_multi_col_freqs(profs, c("Yes", "No"))
prof_freqs <- prof_freqs[c(1,2)]

prof_freqs <- prof_freqs[prof_freqs[2] >= 20, ]
prof_freqs[1] <- as.character(prof_freqs[[1]])
colnames(prof_freqs) <- c("Profession", "Sample size")

recode_vals <- c(
  prof_non_CS = "Non-Civil Service",
  prof_DS_GSG_GORS = "Data Scientist (GSG/GORS)",
  prof_DA_other = "Data Scientist (Non-GSG/GORS)",
  prof_DDAT = "Digital, Data and Technology Profession",
  prof_GAD = "Government Actuary's Department",
  prof_GES = "Government Economic Service",
  prof_finance = "Government Finance Profession",
  prof_geography = "Government Geography Profession",
  prof_GORS = "Government Operational Research Service",
  prof_GSR = "Government Social Research",
  prof_GSG = "Government Statistician Group",
  prof_none_CS = "Civil Service, no profession membership"
  )

prof_freqs$Profession <- dplyr::recode(prof_freqs$Profession, !!!recode_vals)

```

``` {r}

plot_freqs <- prof_freqs
plot_freqs$Profession <- carsurvey2::break_q_names(prof_freqs$Profession)
plot <- carsurvey2::plot_freqs(plot_freqs, "", "Sample size", n = samples$all, orientation = "h", width = 700, height = 700)

table <- kableExtra::kable_styling(knitr::kable(prof_freqs, row.names = FALSE)) %>% 
  kableExtra::add_footnote(paste0("Sample size = ", samples$all))

carsurvey2::wrap_outputs("prof-freqs", plot, table)

```

``` {r}

alphabetical <- as.character(prof_freqs$Profession[order(prof_freqs$Profession)])
urls <- carsurvey2::format_filter_path(alphabetical)
links <- paste0('<li><a href="', urls, '.html">', alphabetical, "</a></li>")
html <- paste(links, collapse="\n\n")
html <- paste0("<ol>", html, "</ol>")
knitr::raw_html(html)

```

