
name: CARS deploy documentation

on:
  release:
    types: [ released ]

jobs:
  deploy-documentation:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish to GitHub Pages
        if: startsWith(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/